export const DEFAULT_THEME_PALETTE = 'professional-slate';
export const DEFAULT_THEME_STYLE = 'standard';

export const THEME_PALETTES = [
  {
    id: 'professional-slate',
    name: 'Professional Slate',
    description: 'Serious, adult, clean, command-center, professional.',
    colors: {
      background: '#F5F7FA',
      surface: '#FFFFFF',
      surfaceSoft: '#EEF3F7',
      text: '#172133',
      mutedText: '#64748B',
      border: '#CBD5E1',
      notes: '#F97316',
      plans: '#14B8A6',
      projects: '#152238',
      success: '#16A34A',
      danger: '#DC2626',
      important: '#F97316',
      sliderCold: '#2563EB',
      sliderHot: '#E11D48',
    },
  },
  {
    id: 'soft-calm',
    name: 'Soft Calm',
    description: 'Soft, calm, gentle, low-stress, readable.',
    colors: {
      background: '#FAF7F2',
      surface: '#FFFFFF',
      surfaceSoft: '#F2EEE7',
      text: '#2F3440',
      mutedText: '#7C8491',
      border: '#D8D0C4',
      notes: '#E6A57E',
      plans: '#8FB9A8',
      projects: '#A69BC6',
      success: '#6EA883',
      danger: '#C76D6D',
      important: '#E6A57E',
      sliderCold: '#7EA8C9',
      sliderHot: '#D9778F',
    },
  },
  {
    id: 'saturated-pop',
    name: 'Saturated Pop',
    description: 'Bright, energetic, modern, colorful.',
    colors: {
      background: '#F8FAFC',
      surface: '#FFFFFF',
      surfaceSoft: '#EEF2FF',
      text: '#151827',
      mutedText: '#5B6475',
      border: '#C7D2FE',
      notes: '#FF6B00',
      plans: '#00BFA6',
      projects: '#7C3AED',
      success: '#22C55E',
      danger: '#EF4444',
      important: '#FF6B00',
      sliderCold: '#0EA5E9',
      sliderHot: '#F43F5E',
    },
  },
  {
    id: 'dark-neon',
    name: 'Dark Neon',
    description: 'Dark mode, neon, focused, cyber, night work.',
    colors: {
      background: '#0B1020',
      surface: '#111827',
      surfaceSoft: '#1F2937',
      text: '#E5E7EB',
      mutedText: '#9CA3AF',
      border: '#334155',
      notes: '#FF8A00',
      plans: '#00E0C6',
      projects: '#8B5CF6',
      success: '#22C55E',
      danger: '#F43F5E',
      important: '#FF8A00',
      sliderCold: '#38BDF8',
      sliderHot: '#FB7185',
    },
  },
  {
    id: 'warm-sunset',
    name: 'Warm Sunset',
    description: 'Warm, human, orange/red/gold, comfortable but active.',
    colors: {
      background: '#FFF7ED',
      surface: '#FFFFFF',
      surfaceSoft: '#FFEDD5',
      text: '#2A1F1A',
      mutedText: '#7C5F53',
      border: '#FED7AA',
      notes: '#EA580C',
      plans: '#D97706',
      projects: '#9A3412',
      success: '#65A30D',
      danger: '#B91C1C',
      important: '#F59E0B',
      sliderCold: '#0284C7',
      sliderHot: '#DC2626',
    },
  },
  {
    id: 'cold-nordic',
    name: 'Cold Nordic',
    description: 'Cool, clean, icy, focused, Scandinavian.',
    colors: {
      background: '#F1F8FC',
      surface: '#FFFFFF',
      surfaceSoft: '#E0F2FE',
      text: '#102A43',
      mutedText: '#627D98',
      border: '#B6D4E8',
      notes: '#0284C7',
      plans: '#0E7490',
      projects: '#3730A3',
      success: '#059669',
      danger: '#BE123C',
      important: '#0EA5E9',
      sliderCold: '#2563EB',
      sliderHot: '#DB2777',
    },
  },
  {
    id: 'adventure-field',
    name: 'Adventure Field',
    description: 'Adventurous, earthy, maps, field notes, exploration.',
    colors: {
      background: '#F7F4EA',
      surface: '#FFFFFF',
      surfaceSoft: '#EDE7D5',
      text: '#263026',
      mutedText: '#6B705C',
      border: '#C9B99A',
      notes: '#B45309',
      plans: '#4D7C0F',
      projects: '#365314',
      success: '#15803D',
      danger: '#B91C1C',
      important: '#CA8A04',
      sliderCold: '#256D85',
      sliderHot: '#A83232',
    },
  },
  {
    id: 'action-hero',
    name: 'Action Hero',
    description: 'Bold, dramatic, comic/action hero, high contrast.',
    colors: {
      background: '#F8FAFC',
      surface: '#FFFFFF',
      surfaceSoft: '#E2E8F0',
      text: '#111827',
      mutedText: '#4B5563',
      border: '#94A3B8',
      notes: '#DC2626',
      plans: '#2563EB',
      projects: '#111827',
      success: '#16A34A',
      danger: '#B91C1C',
      important: '#FACC15',
      sliderCold: '#2563EB',
      sliderHot: '#DC2626',
    },
  },
  {
    id: 'cotton-candy',
    name: 'Cotton Candy',
    description: 'Soft, playful, pink, mint, pastel, friendly.',
    colors: {
      background: '#FFF7FB',
      surface: '#FFFFFF',
      surfaceSoft: '#FCE7F3',
      text: '#372A3A',
      mutedText: '#8B6F8F',
      border: '#F9A8D4',
      notes: '#F472B6',
      plans: '#5EEAD4',
      projects: '#93C5FD',
      success: '#34D399',
      danger: '#FB7185',
      important: '#F9A8D4',
      sliderCold: '#60A5FA',
      sliderHot: '#F472B6',
    },
  },
  {
    id: 'sparkling-arcade',
    name: 'Sparkling Arcade',
    description: 'Sparkling, colorful, playful, arcade/electric.',
    colors: {
      background: '#10101A',
      surface: '#191927',
      surfaceSoft: '#25253A',
      text: '#F8FAFC',
      mutedText: '#B8B8D1',
      border: '#3B3B5C',
      notes: '#F973FF',
      plans: '#00F5D4',
      projects: '#FACC15',
      success: '#22C55E',
      danger: '#FF3864',
      important: '#FACC15',
      sliderCold: '#00BBF9',
      sliderHot: '#F15BB5',
    },
  },
];

export const THEME_STYLES = [
  {
    id: 'standard',
    name: 'Standard',
    description: 'Current app style. Safest default.',
    tokens: {
      radiusCard: '8px',
      radiusButton: '8px',
      radiusInput: '8px',
      radiusSmall: '6px',
      radiusNav: '8px',
      radiusCog: '999px',
      borderWidthCard: '1px',
      borderWidthButton: '1px',
      borderWidthAccent: '6px',
      cardShadow: 'none',
      buttonShadow: 'none',
      surfaceCoverage: '100%',
      panelBlur: '0px',
      cardPadding: '13px',
      framePadding: '10px',
      cardGap: '12px',
      buttonPaddingY: '11px',
      buttonPaddingX: '14px',
      focusRingWidth: '3px',
      fontWeightButton: '700',
    },
  },
  {
    id: 'round',
    name: 'Round',
    description: 'Soft, friendly, pill-shaped, very rounded.',
    tokens: {
      radiusCard: '22px',
      radiusButton: '999px',
      radiusInput: '18px',
      radiusSmall: '14px',
      radiusNav: '999px',
      radiusCog: '999px',
      borderWidthCard: '2px',
      borderWidthButton: '2px',
      borderWidthAccent: '7px',
      cardShadow: '0 10px 26px rgb(15 23 42 / 0.10)',
      buttonShadow: '0 6px 14px rgb(15 23 42 / 0.12)',
      surfaceCoverage: '100%',
      panelBlur: '0px',
      cardPadding: '15px',
      framePadding: '12px',
      cardGap: '13px',
      buttonPaddingY: '11px',
      buttonPaddingX: '16px',
      focusRingWidth: '3px',
      fontWeightButton: '750',
    },
  },
  {
    id: 'minimalist',
    name: 'Minimalist',
    description: 'Clean, simple, quiet, no decoration.',
    tokens: {
      radiusCard: '8px',
      radiusButton: '8px',
      radiusInput: '8px',
      radiusSmall: '5px',
      radiusNav: '8px',
      radiusCog: '8px',
      borderWidthCard: '1px',
      borderWidthButton: '1px',
      borderWidthAccent: '4px',
      cardShadow: 'none',
      buttonShadow: 'none',
      surfaceCoverage: '100%',
      panelBlur: '0px',
      cardPadding: '14px',
      framePadding: '9px',
      cardGap: '13px',
      buttonPaddingY: '10px',
      buttonPaddingX: '13px',
      focusRingWidth: '2px',
      fontWeightButton: '650',
    },
  },
  {
    id: 'edgy',
    name: 'Edgy',
    description: 'Sharp, energetic, slightly aggressive.',
    tokens: {
      radiusCard: '2px',
      radiusButton: '2px',
      radiusInput: '2px',
      radiusSmall: '2px',
      radiusNav: '2px',
      radiusCog: '2px',
      borderWidthCard: '2px',
      borderWidthButton: '2px',
      borderWidthAccent: '8px',
      cardShadow: '0 3px 0 rgb(15 23 42 / 0.18)',
      buttonShadow: '0 2px 0 rgb(15 23 42 / 0.22)',
      surfaceCoverage: '100%',
      panelBlur: '0px',
      cardPadding: '13px',
      framePadding: '10px',
      cardGap: '10px',
      buttonPaddingY: '10px',
      buttonPaddingX: '13px',
      focusRingWidth: '3px',
      fontWeightButton: '800',
    },
  },
  {
    id: 'blocky',
    name: 'Blocky',
    description: 'Chunky, solid, almost game/UI block style.',
    tokens: {
      radiusCard: '6px',
      radiusButton: '6px',
      radiusInput: '6px',
      radiusSmall: '4px',
      radiusNav: '6px',
      radiusCog: '6px',
      borderWidthCard: '3px',
      borderWidthButton: '3px',
      borderWidthAccent: '8px',
      cardShadow: '4px 4px 0 rgb(15 23 42 / 0.18)',
      buttonShadow: '3px 3px 0 rgb(15 23 42 / 0.20)',
      surfaceCoverage: '100%',
      panelBlur: '0px',
      cardPadding: '15px',
      framePadding: '12px',
      cardGap: '10px',
      buttonPaddingY: '12px',
      buttonPaddingX: '15px',
      focusRingWidth: '3px',
      fontWeightButton: '800',
    },
  },
  {
    id: 'hollow',
    name: 'Hollow',
    description: 'Outlined UI, lots of transparent surfaces, border-focused.',
    tokens: {
      radiusCard: '14px',
      radiusButton: '12px',
      radiusInput: '12px',
      radiusSmall: '10px',
      radiusNav: '12px',
      radiusCog: '12px',
      borderWidthCard: '2px',
      borderWidthButton: '2px',
      borderWidthAccent: '6px',
      cardShadow: 'none',
      buttonShadow: 'none',
      surfaceCoverage: '58%',
      panelBlur: '0px',
      cardPadding: '13px',
      framePadding: '10px',
      cardGap: '12px',
      buttonPaddingY: '10px',
      buttonPaddingX: '14px',
      focusRingWidth: '3px',
      fontWeightButton: '750',
    },
  },
  {
    id: 'transparent',
    name: 'Transparent',
    description: 'Light glass-like UI, airy, subtle.',
    tokens: {
      radiusCard: '18px',
      radiusButton: '14px',
      radiusInput: '14px',
      radiusSmall: '12px',
      radiusNav: '14px',
      radiusCog: '999px',
      borderWidthCard: '1px',
      borderWidthButton: '1px',
      borderWidthAccent: '6px',
      cardShadow: '0 10px 30px rgb(15 23 42 / 0.08)',
      buttonShadow: 'none',
      surfaceCoverage: '86%',
      panelBlur: '8px',
      cardPadding: '14px',
      framePadding: '11px',
      cardGap: '12px',
      buttonPaddingY: '10px',
      buttonPaddingX: '14px',
      focusRingWidth: '3px',
      fontWeightButton: '700',
    },
  },
  {
    id: 'boxy',
    name: 'Boxy',
    description: 'Simple rectangles, practical, structured.',
    tokens: {
      radiusCard: '0px',
      radiusButton: '0px',
      radiusInput: '0px',
      radiusSmall: '0px',
      radiusNav: '0px',
      radiusCog: '0px',
      borderWidthCard: '1px',
      borderWidthButton: '1px',
      borderWidthAccent: '5px',
      cardShadow: 'none',
      buttonShadow: 'none',
      surfaceCoverage: '100%',
      panelBlur: '0px',
      cardPadding: '11px',
      framePadding: '8px',
      cardGap: '8px',
      buttonPaddingY: '9px',
      buttonPaddingX: '12px',
      focusRingWidth: '2px',
      fontWeightButton: '700',
    },
  },
  {
    id: 'pro',
    name: 'Pro',
    description: 'Premium productivity tool, polished, serious.',
    tokens: {
      radiusCard: '14px',
      radiusButton: '12px',
      radiusInput: '12px',
      radiusSmall: '9px',
      radiusNav: '12px',
      radiusCog: '999px',
      borderWidthCard: '1px',
      borderWidthButton: '1px',
      borderWidthAccent: '6px',
      cardShadow: '0 12px 32px rgb(15 23 42 / 0.10)',
      buttonShadow: '0 7px 16px rgb(15 23 42 / 0.10)',
      surfaceCoverage: '100%',
      panelBlur: '0px',
      cardPadding: '14px',
      framePadding: '11px',
      cardGap: '12px',
      buttonPaddingY: '10px',
      buttonPaddingX: '14px',
      focusRingWidth: '3px',
      fontWeightButton: '750',
    },
  },
  {
    id: 'hobbyist',
    name: 'Hobbyist',
    description: 'Personal workshop, creative, friendly, tactile.',
    tokens: {
      radiusCard: '16px',
      radiusButton: '14px',
      radiusInput: '12px',
      radiusSmall: '10px',
      radiusNav: '14px',
      radiusCog: '999px',
      borderWidthCard: '2px',
      borderWidthButton: '2px',
      borderWidthAccent: '7px',
      cardShadow: '0 5px 0 rgb(15 23 42 / 0.12)',
      buttonShadow: '0 4px 0 rgb(15 23 42 / 0.15)',
      surfaceCoverage: '100%',
      panelBlur: '0px',
      cardPadding: '14px',
      framePadding: '11px',
      cardGap: '12px',
      buttonPaddingY: '11px',
      buttonPaddingX: '15px',
      focusRingWidth: '3px',
      fontWeightButton: '800',
    },
  },
];

const paletteIds = new Set(THEME_PALETTES.map((palette) => palette.id));
const styleIds = new Set(THEME_STYLES.map((style) => style.id));

export function normalizeThemePaletteId(value) {
  return paletteIds.has(value) ? value : DEFAULT_THEME_PALETTE;
}

export function normalizeThemeStyleId(value) {
  return styleIds.has(value) ? value : DEFAULT_THEME_STYLE;
}

export function getThemePalette(value) {
  const id = normalizeThemePaletteId(value);
  return THEME_PALETTES.find((palette) => palette.id === id) || THEME_PALETTES[0];
}

export function getThemeStyle(value) {
  const id = normalizeThemeStyleId(value);
  return THEME_STYLES.find((style) => style.id === id) || THEME_STYLES[0];
}

function hexToRgb(hex) {
  const clean = String(hex || '').replace('#', '');
  if (clean.length !== 6) return [255, 255, 255];
  return [0, 2, 4].map((start) => parseInt(clean.slice(start, start + 2), 16));
}

function luminance(hex) {
  const [r, g, b] = hexToRgb(hex).map((value) => {
    const channel = value / 255;
    return channel <= 0.03928 ? channel / 12.92 : ((channel + 0.055) / 1.055) ** 2.4;
  });
  return 0.2126 * r + 0.7152 * g + 0.0722 * b;
}

function contrastRatio(colorA, colorB) {
  const lighter = Math.max(luminance(colorA), luminance(colorB));
  const darker = Math.min(luminance(colorA), luminance(colorB));
  return (lighter + 0.05) / (darker + 0.05);
}

function readableTextOn(color) {
  const dark = '#111827';
  const light = '#F8FAFC';
  return contrastRatio(color, dark) >= contrastRatio(color, light) ? dark : light;
}

function setCssVariables(root, variables) {
  Object.entries(variables).forEach(([key, value]) => {
    root.style.setProperty(key, value);
  });
}

export function applyThemeToRoot(paletteId, styleId) {
  if (typeof document === 'undefined') return;

  const palette = getThemePalette(paletteId);
  const style = getThemeStyle(styleId);
  const colors = palette.colors;
  const root = document.documentElement;

  root.dataset.themePalette = palette.id;
  root.dataset.themeStyle = style.id;
  root.style.colorScheme = luminance(colors.background) < 0.3 ? 'dark' : 'light';

  setCssVariables(root, {
    '--app-bg': colors.background,
    '--app-surface': colors.surface,
    '--app-surface-soft': colors.surfaceSoft,
    '--app-text': colors.text,
    '--app-muted': colors.mutedText,
    '--app-border': colors.border,
    '--color-notes': colors.notes,
    '--color-plans': colors.plans,
    '--color-projects': colors.projects,
    '--color-success': colors.success,
    '--color-danger': colors.danger,
    '--color-important': colors.important,
    '--priority-cold': colors.sliderCold,
    '--priority-hot': colors.sliderHot,
    '--on-notes': readableTextOn(colors.notes),
    '--on-plans': readableTextOn(colors.plans),
    '--on-projects': readableTextOn(colors.projects),
    '--on-success': readableTextOn(colors.success),
    '--on-danger': readableTextOn(colors.danger),
    '--on-important': readableTextOn(colors.important),
    '--section-aha': colors.notes,
    '--section-hmm': colors.plans,
    '--section-tada': colors.projects,
    '--section-aha-soft': `color-mix(in srgb, ${colors.notes} 16%, ${colors.surfaceSoft})`,
    '--section-hmm-soft': `color-mix(in srgb, ${colors.plans} 16%, ${colors.surfaceSoft})`,
    '--section-tada-soft': `color-mix(in srgb, ${colors.projects} 14%, ${colors.surfaceSoft})`,
    '--button-bg': colors.plans,
    '--button-text': readableTextOn(colors.plans),
    '--secondary-button-bg': `color-mix(in srgb, ${colors.surfaceSoft} 76%, ${colors.plans})`,
    '--danger-bg': colors.danger,
    '--success-bg': colors.success,
    '--important-bg': colors.important,
    '--header-bg': `color-mix(in srgb, ${colors.background} 94%, transparent)`,
    '--nav-bg': `color-mix(in srgb, ${colors.surface} 96%, transparent)`,
    '--edit-panel-bg': `color-mix(in srgb, ${colors.surfaceSoft} 86%, ${colors.surface})`,
    '--danger-soft': `color-mix(in srgb, ${colors.danger} 12%, ${colors.surface})`,
    '--success-soft': `color-mix(in srgb, ${colors.success} 14%, ${colors.surface})`,
    '--focus-color': colors.important,
  });

  setCssVariables(root, {
    '--radius-card': style.tokens.radiusCard,
    '--radius-button': style.tokens.radiusButton,
    '--radius-input': style.tokens.radiusInput,
    '--radius-small': style.tokens.radiusSmall,
    '--radius-nav': style.tokens.radiusNav,
    '--radius-cog': style.tokens.radiusCog,
    '--border-width-card': style.tokens.borderWidthCard,
    '--border-width-button': style.tokens.borderWidthButton,
    '--border-width-accent': style.tokens.borderWidthAccent,
    '--card-shadow': style.tokens.cardShadow,
    '--button-shadow': style.tokens.buttonShadow,
    '--surface-coverage': style.tokens.surfaceCoverage,
    '--panel-blur': style.tokens.panelBlur,
    '--card-padding': style.tokens.cardPadding,
    '--frame-padding': style.tokens.framePadding,
    '--card-gap': style.tokens.cardGap,
    '--button-padding-y': style.tokens.buttonPaddingY,
    '--button-padding-x': style.tokens.buttonPaddingX,
    '--focus-ring-width': style.tokens.focusRingWidth,
    '--font-weight-button': style.tokens.fontWeightButton,
  });
}
